backend:
  name: github
  repo: FlowerAccepted/FlowerAccepted.github.io
  branch: main
  client_id: ${{ secrets.CMS_CLIENT_ID }}
  client_secret: ${{ secrets.CMS_CLIENT_SECRET }}

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "标题" }
      - { name: "date", label: "日期", widget: "datetime" }
      - { name: "body", label: "正文", widget: "markdown" }
